"C++ Library 훑어보기" 스터디 개설
CppKorea/Studies pull request #9
Opened 2022-06-24 14:28 UTC by luncliff

스터디 관련 안내사항을 공개할 수 있도록 Markdown 문서를 추가합니다.
이후 스터디 진행과정에서 작성하는 문서들은 LibraryReview 폴더를 사용하려 합니다.

2022-06-24 14:50 UTC, utilForever requested changes
오타 및 띄어쓰기를 확인했습니다.

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +따라서 모든 참여인원들이 **1회이상 발표를 진행**할 예정입니다.
```suggestion
따라서 모든 참여 인원들이 **1회 이상 발표를 진행**할 예정입니다.
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +이번 스터디의 목표는 **참여인원들이 C++ 라이브러리를 공부하거나, 사용할 때의 여러 노하우(Know-how)를 공유하는 것**입니다.
```suggestion
이번 스터디의 목표는 **참여 인원들이 C++ 라이브러리를 공부하거나, 사용할 때의 여러 노하우(Know-how)를 공유하는 것**입니다.
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +다만 참여인원이 적을수록 부담이 가중될 수 있기 때문에, 이후 모집 결과에 따라서 1일차 모임에서 함께 토의를 진행하여 확정할 것입니다.
```suggestion
다만 참여 인원이 적을수록 부담이 가중될 수 있기 때문에, 이후 모집 결과에 따라서 1일차 모임에서 함께 토의를 진행하여 확정할 것입니다.
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +각자의 관심범위에 맞게 해당 라이브러리의 예제(sample), 테스트(test), 구현 코드들을 리뷰하여 발표합니다.
```suggestion
각자의 관심 범위에 맞게 해당 라이브러리의 예제(example), 테스트(test), 구현 코드들을 리뷰해 발표합니다.
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +현재는 [https://github.com/OpenImageIO/oiio](https://github.com/OpenImageIO/oiio)프로젝트를 사용해 진행하려 하고 있습니다만, 참여인원들에게 유익한 프로젝트를 리뷰할 수 있도록 의견을 적극적으로 반영하고자 합니다.
```suggestion
현재는 [https://github.com/OpenImageIO/oiio](https://github.com/OpenImageIO/oiio) 프로젝트를 사용해 진행할 예정입니다만, 참여 인원들에게 유익한 프로젝트를 리뷰할 수 있도록 의견을 적극적으로 반영하고자 합니다.
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +이 스터디는 초급지~중급자를 대상으로 하고 있습니다.
```suggestion
이 스터디는 초급자~중급자를 대상으로 하고 있습니다.
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +### 모집대상 및 스터디 난이도
```suggestion
### 모집 대상 및 스터디 난이도
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +* C++ 입문서를 읽고나서 새로운 공부거리를 찾는 사람
```suggestion
* C++ 입문서를 읽고 나서 새로운 공부거리를 찾는 사람
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +참여인원들의 일정이 허용한다면 오프라인으로 모임을 가질 수 있습니다.
```suggestion
참여 인원들의 일정이 허용한다면 오프라인으로 모임을 가질 수 있습니다.
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +온라인 모임은 스터디를 진행하는 운영진이 [Zoom](https://zoom.us/)미팅을 개설하여 참여인원들을 초대하는 방법으로 진행합니다.
```suggestion
온라인 모임은 스터디를 진행하는 운영진이 [Zoom](https://zoom.us/) 미팅을 개설해 참여 인원들을 초대하는 방식으로 진행합니다.
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +    1. 스터디 진행방법에 대한 안내
```suggestion
    1. 스터디 진행 방법에 대한 안내
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +    2. 참여인원 각자의 목표 정하기/공유
```suggestion
    2. 참여 인원 각자의 목표 정하기/공유
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +    2. 중간회고. 진행날짜/방식에 대한 의견 공유 및 조정
```suggestion
    2. 중간 회고. 진행 날짜/방식에 대한 의견 공유 및 조정
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +    1. 스터디 2일차 참여인원 발표
```suggestion
    1. 스터디 2주차 참여 인원 발표
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +    1. 스터디 3일차 참여인원 발표
```suggestion
    1. 스터디 3주차 참여 인원 발표
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +    1. 스터디 5일차 참여인원 발표
```suggestion
    1. 스터디 5주차 참여 인원 발표
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +    1. 스터디 6일차 참여인원 발표
```suggestion
    1. 스터디 6주차 참여 인원 발표
```

2022-06-24 14:50 UTC, utilForever commented on LibraryReview/readme.md
> +    1. 스터디 7일차 참여인원 발표
```suggestion
    1. 스터디 7주차 참여 인원 발표
```

2022-06-24 14:57 UTC, utilForever requested changes
추가로 발견한 오타 및 어색한 표현을 바로잡아 보았습니다.

2022-06-24 14:57 UTC, utilForever commented on LibraryReview/readme.md
> +    1. 스터디 4일차 참여인원 발표
```suggestion
    1. 스터디 4주차 참여 인원 발표
```

2022-06-24 14:57 UTC, utilForever commented on LibraryReview/readme.md
> +이미 존재하는 C++ 라이브러리를 리뷰함으로써 프로그래밍 언어 및 그 외적인 부분에 대한 지식을 더하는데 관심이 있는 분이라면 환영합니다.
```suggestion
이미 존재하는 C++ 라이브러리를 리뷰함으로써 프로그래밍 언어와 외적 지식을 더하는데 관심이 있는 분이라면 환영합니다.
```

2022-06-24 14:57 UTC, utilForever commented on LibraryReview/readme.md
> +모든 것들이 순탄하게 진행된다면 다수의 라이브러리를 리뷰한 모임이 될 수 있으리라 생각합니다.
```suggestion
모든 것들이 순탄하게 진행된다면 여러 라이브러리를 리뷰하는 값진 시간이 될 수 있으리라 생각합니다.
```

2022-06-24 15:01 UTC, utilForever requested changes
이게 마지막일 거 같네요.
그리고 폴더명을 `Library Review`로 바꾸는 건 어떤가요? 띄어쓰기를 안할 이유가 없어 보이는데... ㅇㅅㅇ;

2022-06-24 15:01 UTC, utilForever commented on LibraryReview/readme.md
> +### 목표/진행방식
```suggestion
### 목표 / 진행 방식
```

2022-06-24 15:01 UTC, utilForever commented on LibraryReview/readme.md
> +### 진행일정
```suggestion
### 진행 일정
```

2022-06-24 15:03 UTC, luncliff commented
띄어쓰기 넣는게 더 좋겠네요.

2022-06-24 15:04 UTC, utilForever approved these changes
LGTM now. Thanks for your work! 🎉

2022-06-26 05:24 UTC, utilForever approved these changes
여기도 제목 바꾸면 좋을 거 같아요.

2022-06-26 05:24 UTC, utilForever commented on Library Review/readme.md
> +## "C++ Library 훑어보기" 스터디 모집 안내
```suggestion
## "C++ 라이브러리 훑어보기" 스터디 모집 안내
```

2022-06-26 05:29 UTC, merged